### PR TITLE
Automate deployment with Ansible

### PR DESCRIPTION
**Pull request by alysivji**
Adding Ansible playbook to create a reproducible deployment.

### CODE REVIEW

**Comment by alysivji** [comment]
@kurtiskerstein can you take a look at this?

**Comment by kurtiskerstein** [comment]
Definitely a good start.  Do you plan to use the variables stored in groups_vars across the whole Ansible deploy?  If not... I would move to roles/common/defaults/main.yml

**Comment by kurtiskerstein** [comment]
Another thing you could do...  split up your tasks to be more modular. If your playbooks grow it will be easier to manage.

**Comment by alysivji** [comment]
When you say make tasks more modular, what does that mean?

**Comment by alysivji** [comment]
Spoke to Kurtis on the ChiPy Slack and got tips on refactoring roles to be equivalent to a unit of work.

When running large configurations with jinja templates and values, you want to break up components to have an easy to understand directory structure. When you only run a few things, it doesn't matter as much, but do I really want to run `cron` on each instance? Common should be config you want on all remote instances.

**Pull request merged**
